apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: calculator-application
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  destination:
    namespace: calculator-app
    server: https://kubernetes.default.svc
  project: default
  source:
    path: java
    repoURL: https://github.com/mjekrami/calculator-cd
    targetRevision: HEAD


