# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    events {
      worker_connections 1024;
      }
    http {
      server {
        root /var/www;
        index index.html;
        listen 80;
        location / {
          try_files $uri /index.html
          }
        }
      }
